spring.application.name=recipe
spring.data.mongodb.uri=mongodb://localhost:27017/recipeapp
server.port=8082

recipe.app.jwtCookieName= recipe-app
recipe.app.jwtSecret= ======================Recipe=Spring===========================
recipe.app.jwtExpirationMs= 86400000