version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  spring-app:
    build:
      context: .  # use the Dockerfile in the current directory
      dockerfile: Dockerfile
    container_name: spring-app-container
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/recipeapp
      # other environment variables for Spring Boot app if needed

volumes:
  mongodb-data:
    driver: local
