version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  spring-app:
    image: atharvarthakur/recipe-server:latest
    container_name: spring-container
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/recipeapp
      # other environment variables for Spring Boot app if needed

volumes:
  mongodb-data:
    driver: local
